proximity-radius: 200.0

debug: true

gui:
  title: "&8Chat Mode Selection"

  decoration:
    filler:
      display-name: "&f"
      lore: []

  info:
    material: "LECTERN"
    display-name: "&e&lCHAT INFORMATION"
    lore:
      - "&8Description"
      - ""
      - "&6Current Information:"
      - "&f◆ Player: &e<player>"
      - "&f◆ Current Mode: &e<current_mode>"
      - "&f◆ Local Radius: &e<radius> blocks"
      - ""
      - "&7Click the button below to change mode"

  confirm:
    local-material: "GREEN_WOOL"
    local-display-name: "&a&lSWITCH TO LOCAL"
    local-lore:
      - "&8Description"
      - ""
      - "&6Information:"
      - "&fClick here to switch to"
      - "&fLocal chat mode!"
      - ""
      - "&a◆ &fRange: &a<radius> blocks"
      - "&a◆ &fOnly nearby players will see your messages"
      - ""
      - "&e➡ &l&nCLICK&e to Switch"

    global-material: "BLUE_WOOL"
    global-display-name: "&9&lSWITCH TO GLOBAL"
    global-lore:
      - "&8Description"
      - ""
      - "&6Information:"
      - "&fClick here to switch to"
      - "&fGlobal chat mode!"
      - ""
      - "&9◆ &fRange: &9Unlimited"
      - "&9◆ &fAll players will see your messages"
      - ""
      - "&e➡ &l&nCLICK&e to Switch"

  close:
    material: "RED_WOOL"
    display-name: "&c&lCLOSE"
    lore:
      - "&8Description"
      - ""
      - "&6Information:"
      - "&fClick here to close"
      - "&fthis menu."
      - ""
      - "&e➡ &l&nCLICK&e to Close"

  messages:
    cancelled: "&8[&6Chat&8] &7Menu closed."

messages:
  local-mode: "&8[&6Chat&8] &7Switched to &a&lLocal &7chat mode &8(&a<radius> blocks&8)"
  global-mode: "&8[&6Chat&8] &7Switched to &9&lGlobal &7chat mode &8(&9Unlimited range&8)"
  no-permission: "&8[&6Chat&8] &cInsufficient permissions for local chat. &7Switched to global mode."
  reload-success: "&8[&6ZelChat-Proximity&8] &aConfiguration reloaded successfully!"
  reload-usage: "&8[&6ZelChat-Proximity&8] &cUsage: &f/pzelchat reload|debug"
  no-permission-command: "&8[&6Chat&8] &cInsufficient permissions to use this command."
  no-permission-reload: "&8[&6ZelChat-Proximity&8] &cInsufficient permissions to reload the plugin."
  player-only: "&8[&6Chat&8] &cThis command can only be used by players."